export { default as Logo } from "./logo.svg";
export { default as avatar } from "./avatar.png";
export { default as defaultBg } from "./banner.png";

export { default as NoteIcon } from "./note-icon.svg";
export { default as SaveIcon } from "./save-icon.svg";
export { default as WorkIcon } from "./work-icon.svg";
export { default as SettingIcon } from "./setting-icon.svg";
export { default as PenIcon } from "./pen-icon.svg";
export { default as SmallPenIcon } from "./small-pen-icon.svg";
export { default as CalendarIcon } from "./calendar-icon.svg";
export { default as LocationIcon } from "./location-icon.svg";
export { default as HeartIcon } from "./heart-icon.svg";
export { default as BellPurpleIcon } from "./bell-purple-icon.svg";
export { default as BellRedIcon } from "./bell-red-icon.svg";
export { default as VideoIcon } from "./video-icon.svg";
export { default as RoundPlusIcon } from "./round-plus-icon.svg";
export { default as DocumentIcon } from "./document-icon.svg";
export { default as ImageIcon } from "./image-icon.svg";
